# Generated by Django 3.2.5 on 2023-01-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='uploads_images/', verbose_name='Photo de profil'),
        ),
    ]
