# Generated by Django 3.2.5 on 2023-01-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads_images/', verbose_name='Photo de profil'),
        ),
    ]
