# Generated by Django 3.2.5 on 2023-01-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='uploads_images/img.png', null=True, upload_to='uploads_images/', verbose_name='Photo de profil'),
        ),
    ]
