# Generated by Django 3.2.5 on 2023-01-10 00:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Numero de téléphone'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
