# Generated by Django 3.2.5 on 2023-01-10 01:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionimo', '0002_auto_20230110_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Numero de téléphone'),
        ),
    ]
