# Generated by Django 3.2.5 on 2023-01-10 01:21

from django.db import migrations
import phone_field.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionimo', '0004_alter_locataire_phone_number2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numero de téléphone'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='phone_number2',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Numero de téléphone'),
        ),
    ]
