# Generated by Django 3.2.5 on 2023-01-10 02:27

from django.db import migrations, models
import phone_field.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionimo', '0005_auto_20230110_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='date_location',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numero de téléphone 1 '),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='phone_number2',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Numero de téléphone 2 '),
        ),
    ]
