# Generated by Django 3.2.5 on 2023-01-10 03:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionimo', '0006_auto_20230110_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locataire',
            name='phone_number2',
        ),
        migrations.AlterField(
            model_name='locataire',
            name='loue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionimo.loyer', verbose_name='Loyé'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numero de téléphone'),
        ),
    ]
